src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $surname;

    /**
     * @ORM\Column(type="integer")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mail;

    /**
     * @ORM\Column(type="date")
     */
    private $date_rdv;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $time;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $price;

    /**
     * @ORM\Column(type="boolean")
     */
    private $acceptance;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getDateRdv(): ?\DateTimeInterface
    {
        return $this->date_rdv;
    }

    public function setDateRdv(\DateTimeInterface $date_rdv): self
    {
        $this->date_rdv = $date_rdv;

        return $this;
    }

    public function getTime(): ?string
    {
        return $this->time;
    }

    public function setTime(string $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getAcceptance(): ?bool
    {
        return $this->acceptance;
    }

    public function setAcceptance(bool $acceptance): self
    {
        $this->acceptance = $acceptance;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;



class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => "Nom"
            ])

            ->add('surname', TextType::class, [
                'label' => "Prenom"
            ])

            ->add('phone', TelType::class, [
                'label' => 'Téléphone'
            ])

            ->add('mail',EmailType::class, [
                'label' => 'Mail'
            ])
            ->add('date_rdv', DateType::class,[
                'label' => 'Date RDV',
                'widget' => 'single_text',
                ])
            ->add('time', ChoiceType::class, [
                'label' => 'Heure RDV',
                'choices'  => [
                    '09h00' => '09h00',
                    '10h00' => '10h00',
                    '11h00' => '11h00',
                    '12h00' => '12h00',
                    '13h00' => '13h00',
                    '14h00' => '14h00',
                    '15h00' => '15h00',
                    '16h00' => '16h00',
                    '17h00' => '17h00',
                ],
            ])
            ->add('price', ChoiceType::class, [
                'label' => 'Tarif',
                'choices'  => [
                    'Enfant, Etudiant, tarifs réduits : 15 €' => '15',
                    'Adulte : 20 €' => '20',
                    '6 séances : 60 €' => '60',
                ],
            ])
            ->add('acceptance', CheckboxType::class, [
                'label' => 'J\'autorise la Clinique Oscar à utiliser mes coordonnées 
                uniquement pour me contacter et gérer mon rendez-vous.'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/AppController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class AppController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(): Response
    {
        return $this->render('app/index.html.twig', [
            'controller_name' => 'AppController',
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/reservation")
 */
class ReservationController extends AbstractController
{
    /**
     * @Route("/", name="reservation_index", methods={"GET"})
     */
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->redirectToRoute('reservation_new');
    }

    /**
     * @Route("/new", name="reservation_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {

        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reservation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reservation $reservation): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_delete", methods={"POST"})
     */
    public function delete(Request $request, Reservation $reservation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/app/footer.html.twig
    <footer>
        <div>
            <img src="{{ asset('assets/img/logoEcoleOscar.jpg') }}" alt="Oscar école européenne d'ostéopathie" title="Oscar école européenne d'ostéopathie">
        </div>
        <div class="text-footer">
            <h2>École Oscar</h2>
            <p>Campus Privé d'Alsace</p>
            <p>24a Rue des magasins - 67000 Strasbourg</p>
            <p>Tel: +33 (0)3 88 23 14 14 - info@ecoleoscar.com</p>
        </div>
    </footer>

templates/app/header.html.twig
    <header>
        <div class="flex-header">
            <img class="logo_oscar" src="{{ asset('assets/img/logoCliniqueOscar.jpg') }}" alt="École européenne d'ostéopathie" title="École européenne d'ostéopathie">
            <div>
                <p class="banniere1">Certification</p>
                <img class="logo_ministere" src="{{ asset('assets/img/sante.jpg') }}" alt="Agréée par le Ministère des affaires sociales et de la santé" title="Agréée par le Ministère des affaires sociales et de la santé">
                <p class="banniere2">Prenez rendez-vous</p>
            </div>
        </div>

        <div class="zone-reservation">
            <h1 class="reservation">Reservez une consultation ostéopathique</h1>
        </div>
    </header>

templates/app/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

      {{ include('app/header.html.twig') }}

    <body onload="On_date()">

    <main>

        <p>L’école est située au centre-ville de Strasbourg, et a pour vocation de former des ostéopathes
            dans le respect des valeurs de l’ostéopathie et de la protection des patients. </p>

        <p>OSCAR dispense un enseignement de l’ostéopathie de haut niveau pour encadrer ses étudiants à devenir des praticiens confirmés et diplômés.</p>

        <p>La démarche pédagogique d’OSCAR est unique.</p>

        <p>Des intervenants expérimentés initient selon un haut niveau de connaissance un enseignement théorique et pratique.</p>

        <img class="student" src="{{ asset('assets/img/student.jpg') }}" alt="oscar">

        <p>Le but étant de former un véritable professionnel capable dès la sortie du cursus de prendre en charge des patients
            pour diagnostiquer et traiter les lésions ostéopathiques.</p>

        <p>Tout ceci en garantissant la sécurité et la qualité des soins au patient.</p>

        <p>L’ostéopathie à tout âge de la vie : l’ostéopathie choisit la technique la mieux adaptée et la plus confortable pour chaque patient,
            en fonction de son âge et de sa morphologie et de la zone du corps à corriger.<p>

        <p>Il peut traiter le nourrisson, l’enfant, l’adulte comme la personne âgée.</p>

        <div class="space"></div>
        <a class="link" href="{{ path('reservation_new') }}">Prendre RDV</a>
        <div class="space"></div>
    </main>

    {{ include('app/footer.html.twig') }}

{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="robots" content="INDEX,FOLLOW" />
            <meta name="theme-color" content="#ffffff">
            <meta name="author" content="Passeri Mario" />
            <meta name="copyright" content="Passeri Mario" />
            <meta name="geo.placename" content="Strasbourg, Alsace">
            <meta name="geo.country" content="FR">
            <title>{% block title %}Formulaire training{% endblock %}</title>
            <link rel="shortcut icon" href="{{ asset('assets/img/svg/logo.svg') }}" type="image/x-icon">
            <meta name="description" content="micro app formulaire d'entrainement de reservation">
            {% block stylesheets %}
                <link href="{{ asset('assets/css/normalize.css') }}" rel="stylesheet">
                <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet">
            {% endblock %}

            {% block javascripts %}
                <!-- JS -->
                <script src="{{ asset('assets/js/jquery.js') }}"></script>
                <script src="{{ asset('assets/js/app.js') }}"></script>
            {% endblock %}
        </head>
    <body>
    {% block body %}{% endblock %}
    </body>
</html>

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Êtes-vous sûr de bien vouloir supprimer votre rendez-vous ? ');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Supprimer mon rendez-vous</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}
    <div class="flexi-form">
        {{ form_label(form.name, null, {'label_attr': {'class': 'foo'} }) }}
        {{ form_widget(form.name, {'attr': {'class': 'float_input'}}) }}
    </div>

    <div class="flexi-form">
        {{ form_label(form.surname, null, {'label_attr': {'class': 'foo'} }) }}
        {{ form_widget(form.surname, {'attr': {'class': 'float_input'}}) }}
    </div>

    <div class="flexi-form">
        {{ form_label(form.phone, null, {'label_attr': {'class': 'foo'} }) }}
        {{ form_widget(form.phone, {'attr': {'class': 'float_input'}}) }}
    </div>

    <div class="flexi-form">
        {{ form_label(form.mail) }}
        {{ form_widget(form.mail, {'attr': {'class': 'float_input'}}) }}
    </div>

    <div class="flexi-form">
        {{ form_label(form.date_rdv) }}
        {{ form_widget(form.date_rdv, {'id': 'date','attr': {'class': 'float_input_date'}}) }}
    </div>

    <div class="flexi-form">
        {{ form_label(form.time) }}
        {{ form_widget(form.time, {'attr': {'class': 'float_input'}}) }}
    </div>

    <div class="flexi-form">
        {{ form_label(form.price) }}
        {{ form_widget(form.price, {'attr': {'class': 'float_input'}}) }}
    </div>

    <div class="flexi-form">
        {{ form_widget(form.acceptance, {'attr': {'class': 'Autorisation close'}}) }}
        {{ form_label(form.acceptance, null, {'label_attr': {'class': 'texte-autorisation'} }) }}
    </div>

{{ form_rest(form) }}

<button class="submit">{{ button_label|default('Valider RDV') }}</button>

{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('reservation_index') }}">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation index{% endblock %}

{% block body %}
    <h1>Reservation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Phone</th>
                <th>Mail</th>
                <th>Date_rdv</th>
                <th>Time</th>
                <th>Price</th>
                <th>Acceptance</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.name }}</td>
                <td>{{ reservation.surname }}</td>
                <td>{{ reservation.phone }}</td>
                <td>{{ reservation.mail }}</td>
                <td>{{ reservation.dateRdv ? reservation.dateRdv|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ reservation.time }}</td>
                <td>{{ reservation.price }}</td>
                <td>{{ reservation.acceptance }}</td>
                <td>
                    <a href="{{ path('reservation_show', {'id': reservation.id}) }}">show</a>
                    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('reservation_new') }}">Create new</a>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ include('app/header.html.twig') }}

<body onload="On_date()">

<main>
    <div class="space"></div>
    <a class="link" href="{{ path('home') }}">Retour</a>
    <div class="space"></div>

    <p>Chaque consultation dure environ 45 minutes.</p>
    <ul>
        <li>15 € pour les enfants, les étudiants et les tarifs réduits</li>
        <li>20 € pour le tarif adulte</li>
        <li>60 € pour 6 séances</li>
    </ul>
    <p>En clinique les soins dispensés par nos étudiants encadrés<br> par des <strong>enseignants ostéopathes professionnels</strong>.</p>
    <p>Merci de renseigner les champs ci-dessous.</p>

    {{ include('reservation/_form.html.twig') }}
</main>

{{ include('app/footer.html.twig') }}

{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ include('app/header.html.twig') }}

<body onload="On_date()">
    <main>
        <h2>Votre reservation Numéro : {{ reservation.id }}</h2>

        <p>Bénéficiez d’une prise en charge toute l’année, du lundi au samedi, par des étudiants confirmés et encadrés par des ostéopathes expérimentés.</p>

        <hr>

        <h3>Vos informations :</h3>

        <table class="table">
            <tbody>
            <tr>
                <th>Nom :</th>
                <td>{{ reservation.name }}</td>
            </tr>
            <tr>
                <th>Prenom :</th>
                <td>{{ reservation.surname }}</td>
            </tr>
            <tr>
                <th>Téléphone :</th>
                <td>0{{ reservation.phone }}</td>
            </tr>
            <tr>
                <th>Email :</th>
                <td>{{ reservation.mail }}</td>
            </tr>
            <tr>
                <th>Rendez-vous :</th>
                <td>{{ reservation.dateRdv ? reservation.dateRdv|date('d/m/Y') : '' }}</td>
            </tr>
            <tr>
                <th>Heure  : </th>
                <td>{{ reservation.time }}</td>
            </tr>
            <tr>
                <th>Tarification :</th>
                <td>{{ reservation.price }} €</td>
            </tr>
            <tr>
                <th>Consentement :</th>
                {% if reservation.acceptance == 1 %}
                    <td>Concentement approuvé</td>
                {% else %}
                    <td>Concentement refusé</td>
                {% endif %}
            </tr>
            </tbody>
        </table>

        <p>Supprimer votre consultation d’ostéopathie en ligne 24h/24</p>

        {{ include('reservation/_delete_form.html.twig') }}

        {#<a href="{{ path('reservation_index') }}">back to list</a>

        <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">edit</a>

        {{ include('reservation/_delete_form.html.twig') }}#}
    </main>

    {{ include('app/footer.html.twig') }}

{% endblock %}